/**
 * Converts the original `data/words.csv` (a line-per-word dump, not real CSV)
 * into a typed TypeScript module the app can import directly, avoiding any
 * CSV parsing at runtime. Run with `pnpm generate:words`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const rootDir = fileURLToPath(new URL('..', import.meta.url))
const sourcePath = `${rootDir}data/words.csv`
const outputPath = `${rootDir}src/data/words.ts`

const letterRun = /\p{L}+/u

function extractWord(line: string): string | null {
  const match = letterRun.exec(line)
  return match ? match[0].toUpperCase() : null
}

const lines = readFileSync(sourcePath, 'utf-8').split('\n')
const words = lines.map(extractWord).filter((word): word is string => word !== null)

if (words.length === 0) {
  throw new Error('No words extracted from data/words.csv')
}

const banner = `// Generated by scripts/generate-words.ts from data/words.csv. Do not edit by hand.\n`
const body = `export const WORDS: readonly string[] = ${JSON.stringify(words)} as const\n`

writeFileSync(outputPath, banner + body)

console.log(`Generated ${words.length} words -> ${outputPath}`)
